config/routes.rb
Rails.application.routes.draw do
  resources :likes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:                  "top#index"
  resources                 :users do
    resources               :relation, only: [:create, :destroy]
  end

  resources                 :tweets do
    resources               :likes, only: [:create, :destroy]
  end

  get "users/index/:id" =>  "user#index"
  get "users/show/:id" =>   "users#show"
  get "relationed/:id" =>   "relation#showed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :follow, class_name: "User", counter_cache: :follow_count
  belongs_to :followed, class_name: "User", counter_cache: :follower_count
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to                  :user
  has_many                    :likes, dependent: :destroy
  validates_presence_of       :title, :text

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :relations, foreign_key: :follow_id

  has_many :tweets

  def follow_user(user)
    Relation.find_by(follow_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :login_require

  def login_require
    # redirect_to root_path unless current_user
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: @tweet.id)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, tweet_id: @tweet.id).destroy
  end

  private
  def set_like
    @tweet = Tweet.find(params[:tweet_id])
    @likes = Like.where(tweet_id: @tweet.id)
  end

end

app/controllers/relation_controller.rb
class RelationController < ApplicationController
  before_action :set_follow, only: [:create]
  before_action :set_unfollow, only: [:destroy]

  def show
    #フォロー 一覧表示
    @users = Relation.where(follow_id: current_user.id)
    @userss = []
    @users.each do |user|
      @userss << User.find(user.followed_id)
    end
  end

  def showed
    #フォロワー 一覧
    @users = Relation.where(followed_id: current_user.id)
    @userss = []
    @users.each do |user|
      @userss << User.find(user.follow_id)
    end
  end

  def create
    #フォローするアクション
    @follow = Relation.create(follow_id: current_user.id, followed_id: @user.id)
  end

  def destroy
    #フォロー外すアクション
    @unfollow = Relation.find_by(follow_id: current_user.id).destroy
  end

  private
  def set_follow
    @user = User.find(params[:format])
  end

  def set_unfollow
    @user = User.find(params[:id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @like = Like.find_by(tweet_id: @tweet.id)
  end

  def create
    @tweet = Tweet.create(tweet_params)
    redirect_to @tweet
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet = Tweet.create(tweet_params)
    redirect_to @tweet
  end

  def destroy
    @tweet = Tweet.find(params[:id]).destroy
    redirect_to '/tweets'
  end

  private
    def tweet_params
      params.require(:tweets).permit(:title, :text, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simple Tweet
    %meta{charset: "utf-8"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags

  %body
    %header
      %h1 Simple Tweet
      %div
        - if user_signed_in?
          %h2 こんにちは！ #{current_user.id}さん
          =link_to "サインアウトはこちら", destroy_user_session_path, method: :delete
          %br
          =link_to "マイページはこちら", user_path(current_user)
        - else
          =link_to "新規登録", new_user_registration_path
          または、
          =link_to "既にアカウントをお持ちの方はこちら", new_user_session_path

    = yield

app/views/likes/_like.html.haml
- if tweet.like_user(current_user.id)
  = button_to tweet_like_path(tweet.id, like.id), method: :delete, remote: true do
    お気に入りをやめる。
  %p
    お気に入り回数 →
    = @tweet.likes_count
- else
  = button_to tweet_likes_path(tweet.id), method: :post, remote: true do
    お気に入りをする。
  %p
    お気に入りの数 →
    = @tweet.likes_count

app/views/likes/create.js.erb
$('#like-buttons').html(
  "<%= j(render partial: 'likes/like', locals: { tweet: @tweet, like: @like }) %>"
  );

app/views/likes/destroy.js.erb
$('#like-buttons').html(
  "<%= j(render partial: 'likes/like', locals: { tweet: @tweet, like: @like }) %>"
  );

app/views/relation/_follow.html.haml
- if user.follow_user(current_user)
  = button_to user_relation_path(user.id, other_user.id),method: :delete, remote: true do
    フォローをやめる。
- else
  = button_to user_relation_index_path(user.id, other_user.id), method: :post,remote: true do
    フォローする。

app/views/relation/create.js.erb
$('#follow-btn').html(
  "<%= j(render partial: 'relation/follow', locals: { user: current_user, other_user: @user }) %>"
  );

app/views/relation/destroy.js.erb
$('#follow-btn').html(
  "<%= j(render partial: 'relation/follow', locals: { user: current_user, other_user: @user }) %>"
  );

app/views/relation/show.html.haml
%h3 あなたのフォロー一覧です！
%p フォローしているユーザーを一覧表示する。つまり、現在ログインしているユーザー(current_user_id)と、Relationテーブルの follow_id カラムから探す(where)。それらのレコードを配列で取り出してきて、.each do || で、ハッシュにする。そのレコードの followed_idの情報を元に、Userテーブルから どのユーザーをフォローしているのか探す(find)。それらのレコードたちを、再度配列(変数)(@userss << )に入れる。それを viwe で.each do!!!!

app/views/relation/showed.html.haml
%h3 あなたの フォロワー 一覧です!!!!
%p followされている相手を書き出していく。つまり、Relation テーブルから、follow_id カラムから、自分のuser.idを探す。(テーブル名.where)配列,変数(@users)で取り出す。後に、空の配列を創る。(@userss = []) 先程取り出した配列(@users)を、ハッシュにする(@users.each do |user|) ハッシュにしたら、変数(配列で)にぶち込む！！！

app/views/top/index.html.haml
%p 教えてもらいながら、作成しています。

%h1 こんにちは!! これは、Simple Tweet です。

%div
  -if user_signed_in?
    %p= link_to "つぶやく!!!!", new_tweet_path
    %p= link_to "つぶやき 一覧", tweets_path
    %p= link_to "ユーザー 一覧", users_path
  -else
    %p 使いたいなら、ログインしなさいな。
    %p simple tweetのユーザー一覧を見れたり、つぶやいたり、フォローしたりできまする。

app/views/tweets/edit.html.haml
%h1 投稿の編集
%p つぶやきを編集しまする!!!!
= form_for :tweets, url: tweet_path, method: :patch do |f|
  = f.hidden_field :user_id, :value => current_user.id.to_i
  %p
    = f.label :title, "つぶやきのタイトル"
    %br/
    = f.text_field :title
  %p
    = f.label :text, "つぶやきの本文"
    %br/
    = f.text_area :text, cols: 60, rows: 8
  %p
    = f.submit "ていせいっ!!!!!!!!!!!!!!!"
%p
  = link_to "戻るで", :back

app/views/tweets/index.html.haml
%h1 全てのTweetです！
%p
  = link_to "つぶやく!!!!!!", new_tweet_path
%table
  %table{:border => "1"}
    %tr
      %th 投稿者
      %th タイトル
      %th 投稿内容
      %th etc...
    - @tweets.each do |tweet|
      %tr
        %td= tweet.user_id
        %td= tweet.title
        %td= tweet.text
        %td= link_to "詳細へ", tweet_path(tweet.id)
  %p
    = link_to "戻るで", :back

app/views/tweets/new.html.haml
%h1 新しい投稿
%p ここにアナタの気分を呟こう呟こう!!!!!!!!!
= form_for :tweets, url: tweets_path do |f|
  = f.hidden_field :user_id, :value => current_user.id.to_i
  %p
    = f.label :title, "つぶやきのタイトル"
    %br/
    = f.text_field :title
  %p
    = f.label :text, "つぶやきの本文"
    %br/
    = f.text_area :text, cols: 60, rows: 8
  %p
    = f.submit "そーーーーーーーしん!!!!!!!!!!!!!!!"
%p
  = link_to "戻るで", :back

app/views/tweets/show.html.haml
%p
  ユーザー :
  \#{@tweet.user_id}
%p
  タイトル :
  \#{@tweet.title}
%p
  つぶやき内容 :
  \#{@tweet.text}
%div{id: "like-buttons"}
  = render partial: 'likes/like', locals: { tweet: @tweet, like: @like }
%p= link_to "編集する", edit_tweet_path(params[:id])
%p= link_to "削除する", tweet_path, method: :delete, data: { confirm: '削除しますか？' }
%p= link_to "一覧に戻るで", tweets_path

app/views/users/index.html.haml
%h3 Simple Tweet ユーザー 一覧 です
- @users.each do |user|
  %table{:border => "1", :width => "50%"}
    %tr
      %td ID number
      %td user info
      %td more...
    %tr
      %td
        囚人番号 #{user.id}
      %td
        = user.email
        さん
      %td= link_to "詳しく", user_path(user.id)
%br/
= link_to "戻るで", :back

app/views/users/show.html.haml
%h1
  = @user.id
  さんのページ
- if current_user.id.to_s == params[:id]
  %h3 あなたのマイページでする
- else
  %div{id: "follow-btn"}
    = render partial: 'relation/follow', locals: { user: current_user, other_user: @user }
%p
  = link_to "つぶやく!!!!!!", new_tweet_path
%p
  = link_to "つぶやき一覧はこっち!", tweets_path
%p
  = link_to "Simple Tweet ユーザー 一覧", users_path